- name: Setup NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_16.x | bash

- name: Install required dependencies for nodejs
  ansible.builtin.yum:
    name:
      - libstdc++.so.6
      - libm.so.6
      - libc.so.6
    state: present

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include App Pre Setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-pre-setup

- name: Install NodeJS dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Include SystemD
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd



